### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by magskull** [DaviMarta/Automatiza-o#11]
Estou rodando em Windows 10, pelo VSCode.
Python: 3.11.1 64 Bit

Apesar de a saida no terminal mostrar informações identificadas, ao final da execução não é possível criar os arquivos, resultando nas seguintes mensagens de erro:

> Traceback (most recent call last):
>   File "c:\Users\Luiz Fernando\Downloads\Automatiza-o-master\Automatiza-o-master\Web-Scraping Google Maps #1.py", line 158, in <module>    merged_df = pd.concat(df_list)
>                 ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Luiz Fernando\AppData\Roaming\Python\Python311\site-packages\pandas\util\_decorators.py", line 331, in wrapper        
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Luiz Fernando\AppData\Roaming\Python\Python311\site-packages\pandas\core\reshape\concat.py", line 368, in concat      
>     op = _Concatenator(
>          ^^^^^^^^^^^^^^
>   File "C:\Users\Luiz Fernando\AppData\Roaming\Python\Python311\site-packages\pandas\core\reshape\concat.py", line 425, in __init__    
>     raise ValueError("No objects to concatenate")
> ValueError: No objects to concatenate

**Comment by magskull** [comment]
Notei que surge um erro durante o debug do código, na linha 129 :  (spatial_df = csv_to_point(non_spatial_data))

`NameError("name 'spatial_df' is not defined")`

**Comment by magskull** [comment]
Agora consegui fazer com que o codigo rode, defini os caminhos por completo, porem ainda persiste o erro acima .
Os arquivos, apesar de serem gerados ficam vazios.

Durante o debug, noto que alguns arquivos são preenchidos mas ficam limpos ao final da execução.

**Comment by magskull** [comment]
Finalmente consegui, tive que colocar o caminho completo em todos trechos que leem ou escrevem arquivos.

Erros de principiante.
